const test = () => {
  const user = null

  console.log(user)

  throw new Error('Este erro Ã© interno!!')
}

module.exports = {
  test
}
